export default  {
	products: [{
		_id: '1' ,
		name: 'Sneakers',
		price: 200,
		brand: 'Nike',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:
			'https://res.cloudinary.com/kwesiblack/image/upload/v1594072607/products/chucks-153310__340_vflesl.png',
		category: 'Shoes',
		trending: true,
		status: 'In Stock',
	},
	{
		_id: '2' ,
		name: 'EyeRe',
		price: 200,
		brand: 'Ray-Bann',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:
			'https://res.cloudinary.com/kwesiblack/image/upload/v1594072606/products/woman-1246299__340_jgflly.jpg',
		category: 'Accessories',
		trending: true,
		status: 'In Stock',
	},
	{
		_id: '3',
		name: 'Patek',
		price: 200,
		brand: 'Patek Philip',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:
			'https://res.cloudinary.com/kwesiblack/image/upload/v1594072606/products/wrist-watch-2159351__340_clhtdu.jpg',
		category: 'Accessories',
		trending: true,
		status: 'In Stock',
	},

	{
		_id: '4',
		name: 'Fur Winter',
		price: 200,
		brand: 'Versace',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:'https://res.cloudinary.com/kwesiblack/image/upload/v1594400596/products/model-600238__340-removebg-preview_ar4yyw.png',
		category: 'Clothing',
		trending: false,
		status: 'In Stock',

	},
	{
		_id: '5',
		name: 'The Hat',
		price: 200,
		brand: 'Victoria Secrets',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:
			'https://res.cloudinary.com/kwesiblack/image/upload/v1594400898/products/fashion-2309519__340-removebg-preview_jfbdfu.png',
		category: 'Hats',
		trending: false,
		status: 'In Stock',

	},
	{
		_id: '6' ,
		name: 'SneakersII',
		price: 200,
		brand: 'Nike',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:'https://res.cloudinary.com/kwesiblack/image/upload/v1594072607/products/chucks-153310__340_vflesl.png',
		category: 'Shoes',
		trending: false,
		status: 'In Stock',

	},
	{
		_id: '7' ,
		name: 'Sweater',
		price: 200,
		brand: 'Victoria Secrets',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:'https://res.cloudinary.com/kwesiblack/image/upload/v1594400901/products/people-2563491__340-removebg-preview_avjvzl.png',
		category: 'Clothing',
		trending: false,
		status: 'In Stock',

	},
	{
		_id: '8',
		name: 'PatekII',
		price: 200,
		brand: 'Patek Philip',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:'https://res.cloudinary.com/kwesiblack/image/upload/v1594072606/products/wrist-watch-2159351__340_clhtdu.jpg',
		category: 'Accessories',
		trending: false,
		status: 'In Stock',

	},
	{
		_id: '9',
		name: 'Fur WinterII',
		price: 200,
		brand: 'Versace',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:'https://res.cloudinary.com/kwesiblack/image/upload/v1594072607/products/fashion-1063100__340_zq91eo.jpg',
		category: 'Clothing',
		trending: true,
		status: 'In Stock',
	},
	{
		_id: '10',
		name: 'Carbon Earing',
		price: 200,
		brand: 'Victoria Secrets',
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam purus nisl, faucibus interdum accumsan vitae, interdum sed felis. Aenean a elit pellentesque, vestibulum neque id, suscipit libero. Mauris posuere sit amet quam in venenatis. Donec convallis hendrerit consectetur. Etiam ac eros non ipsum tincidunt semper et et augue. In eget leo urna. Donec convallis, neque vel laoreet ultrices, magna ipsum congue dui, vel congue lacus massa ac mauris. Integer molestie scelerisque purus. Sed in vestibulum eros. In hac habitasse platea dictumst. Duis feugiat, nisl vitae vulputate consectetur, nisl metus tempus nisi, vel ornare enim risus id neque.',
		image:'https://res.cloudinary.com/kwesiblack/image/upload/v1594416688/products/girl-1868930__340_r2dejv.jpg',
		category: 'Accessories',
		trending: true,
		status: 'In Stock',
	},
],
}


